### ISSUE TITLE
Tudatpy version offered by anaconda not the same as the one described in the "latest" docs?

### ISSUE THREAD

**Issue by Adrianoliverehren** [tudat-team/tudatpy-feedstock#14]
Steps to recreate issue:

1. Install tudatpy using the environment.yaml file offered on the tudat website
2. Import environment_setup
```
from tudatpy.kernel.numerical_simulation import propagation_setup
```
3. Run ```propagation_setup.integrator.runge_kutta_fixed_step(*args)``` - this function does not exist error will appear

This is also true for other functions such as ```environment_setup.rigid_body()```

I wrote some code using tudat in May/June 2023 using these functions and at the time it ran. Recently I had to reinstall tudat and the version currently offered did not have these functions even though the docs say these functions should exist (in the version labeled "latest"). I tried installing the specific builds of tudat available on the anaconda website (0.7.3-py310hee2ac88_3 for example) hoping that these would contain the functions described in the docs but I can't seem to find the correct build.

Which build should I install from conda in order to match the version labeled "latest" on the docs?

**Comment by DominicDirkx** [comment]
The 'latest' version on the API reference corresponds to the dev version of the conda package:

https://docs.tudat.space/en/latest/_src_getting_started/installation.html#installing-tudat-py

We will merge this into the regular packages in thecoming weeks. Let me know if this helps you out!

P.s. in the future, these questions are better suited to the tudatpy repo: https://github.com/tudat-team/tudatpy

**Comment by Adrianoliverehren** [comment]
Right, that makes sense. Thanks for the quick reply
