### ISSUE TITLE
Dependency conflicts on osx

### ISSUE THREAD

**Issue by ggarrett13** [tudat-team/tudatpy-feedstock#2]
For some reason, installing via on **osx**:

````
conda install tudatpy -c tudat-team
````

Is presenting some dependency issues on osx with conda. There is a temporary fix until this is sorted:

````
conda install tudatpy -c tudat-team -c conda-forge -c defaults
````
This applies to updating as well:

````
conda update tudatpy -c tudat-team -c conda-forge -c defaults
````

**Comment by transferorbit** [comment]
I’ve just tried to run a `tutorial_1.py` file from May 2020 with today’s version of TudatPay (via jupyterlab). I get the following error:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-2ca33e4975a8> in <module>
      1 # Initial imports and kernel setup
      2 import numpy as np
----> 3 from tudatpy import spice_interface
      4 
      5 spice_interface.load_standard_spice_kernels()

ImportError: cannot import name 'spice_interface' from 'tudatpy' (/Users/kevin/opt/miniconda3/envs/tudat-space/lib/python3.8/site-packages/tudatpy/__init__.py)
```

The installation process is documented in the attached file.
[installNotes_tudatpy_20200929.txt](https://github.com/tudat-team/tudatpy-feedstock/files/5298955/installNotes_tudatpy_20200929.txt)

For what it’s worth, I have:
   - a very slightly older version of conda running (see attached file)
   - not yet tried `conda install tudatpy -c tudat-team`

**Comment by ggarrett13** [comment]
Hi Kevin, the API has changed significantly since then. Could you try run it with [this version](https://github.com/tudat-team/tudatpy/blob/master/tudatpy/tutorial_1.py) of `tutorial_1.py`? The tutorials will be versioned appropriately soon.

**Comment by transferorbit** [comment]
It appears that this issue has been fixed. Please re-open if this is no the case.
