### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Marchesini010126** [tudat-team/tudatpy-feedstock#7]
Hi Everyone

My computer crashed a few days ago and I had to reinitialise everything.
I am trying to resent tudat on my virtual environment `astrodynamic_venv` but I am having the following error when I run my scripts using the virtual environment with tudatpy installed

```
Traceback (most recent call last):
  File "/Users/gregorio/Desktop/Thesis/code/python/test/dynamic_models_test.py", line 6, in <module>
    import src.dynamic_models as dynamic_models
  File "/Users/gregorio/Desktop/Thesis/code/python/src/dynamic_models.py", line 7, in <module>
    from   conversions_tools import implicit2classic_keplerian_elements,classic2implicit_keplerian_elements,classic2implicit_keplerian_elements_pointwise
  File "/Users/gregorio/Desktop/Thesis/code/python/src/conversions_tools.py", line 5, in <module>
    from tudatpy.kernel.astro     import element_conversion
  File "/Users/gregorio/anaconda3/envs/astrodynamics_venv/lib/python3.8/site-packages/tudatpy/__init__.py", line 2, in <module>
    from .kernel import constants
ImportError: dlopen(/Users/gregorio/anaconda3/envs/astrodynamics_venv/lib/python3.8/site-packages/tudatpy/kernel.so, 0x0002): Library not loaded: @rpath/libnrlmsise00.dylib
  Referenced from: /Users/gregorio/anaconda3/envs/astrodynamics_venv/lib/python3.8/site-packages/tudatpy/kernel.so
  Reason: tried: '/Users/gregorio/anaconda3/envs/astrodynamics_venv/lib/python3.8/site-packages/tudatpy/../../../libnrlmsise00.dylib' (no such file), '/Users/gregorio/anaconda3/envs/astrodynamics_venv/lib/python3.8/site-packages/tudatpy/../../../libnrlmsise00.dylib' (no such file), '/Users/gregorio/anaconda3/envs/astrodynamics_venv/lib/libnrlmsise00.dylib' (no such file), '/Users/gregorio/anaconda3/envs/astrodynamics_venv/bin/../lib/libnrlmsise00.dylib' (no such file), '/Users/gregorio/anaconda3/envs/astrodynamics_venv/lib/libnrlmsise00.dylib' (no such file), '/Users/gregorio/anaconda3/envs/astrodynamics_venv/bin/../lib/libnrlmsise00.dylib' (no such file), '/usr/local/lib/libnrlmsise00.dylib' (no such file), '/usr/lib/libnrlmsise00.dylib' (no such file)
```

I installed tudatpy following the conda installation procedure suggested in this section

https://docs.tudat.space/en/stable/_src_getting_started/installation.html#:~:text=Are%20you%20a%20macOS%20user%3F

And I can see that `conda list` has tudatpy as uploaded package

[venv_packages_list.txt](https://github.com/tudat-team/tudatpy-feedstock/files/8538399/venv_packages_list.txt)
I hope this information is sufficient to give you a full understanding of the error source, otherwise just tell me 

Thank you for your time and attention

**Comment by DominicDirkx** [comment]
Hi Greg, it seems that your conda environment is missing NRLMSISE, and also that you have a rather old version installed. Could you provide some details on the system you are installing it on, and how you installed tudat? Did you try to update an existing environment, or did you create a new one?

**Comment by Marchesini010126** [comment]
Hey Dominic

I had my computer completely cleaned yesterday so it may be that something is off 
My specifics are the following 

1. My computer is a macOS with macOS Monterey as the operating system
2. I had to define a new environment using `conda create`

Maybe I should try to update NRLMSISE
I must be honest in saying that I don't know what it is and why I have such an old version. But I can try

**Comment by Marchesini010126** [comment]
Also The installation procedure was 
`conda install tudatpy matplotlib -c tudat-team -c conda-forge -c defaults`

**Comment by DominicDirkx** [comment]
Hi Greg, try the nominal installation procedure with the yaml file:

https://docs.tudat.space/en/stable/_src_getting_started/installation.html#installing-tudat-py

the command you have comes from the warning box, which I'm not sure is up to date. If you installed tudat in your base environment, make sure to clear this first.

**Comment by Marchesini010126** [comment]
Ok Dominic 
Everything is fixed now 
Thank you for the advice and for your time 

Have a super day
Have a great day !
